export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  const { pin, config } = req.body || {};
  const validPins = ['yamaha1_2', 'nopyasik991'];

  if (!pin || !validPins.includes(String(pin).trim())) {
    return res.status(401).json({ error: 'Password Admin salah!' });
  }

  if (!config) {
    return res.status(400).json({ error: 'Config data missing.' });
  }

  const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
  const REPO = 'justtopia4-tech/MagicalPS';

  const configTxtContent = `# ====================================================
# CONFIGURATION FILE FOR MAGICAL WEBSITE
# Auto-generated by Admin Dashboard (/admin)
# ====================================================

# IP Server & Domain Host
HOST_IP=${config.hostIp || ''}
HOST_DOMAIN=${config.hostDomain || 'www.growtopia1.com'}

# Link HOST Android (PowerTunnel), iOS (Surge 5) & APK GTPS
VHOST_ANDROID_URL=${config.vhostAndroidUrl || ''}
VHOST_IOS_URL=${config.vhostIosUrl || ''}
APK_URL=${config.apkUrl || ''}
HOST_TXT_CONTENT=${(config.hostTxtContent || '').replace(/\n/g, '\\n')}

# Kontak & Komunitas
WHATSAPP_NUMBER=${config.whatsappNumber || ''}
WHATSAPP_GROUP_LINK=${config.whatsappGroupLink || ''}
DISCORD_INVITE=${config.discordInvite || ''}

# Profil Server
PROFILE_HANDLE=${config.profileHandle || 'Magical Private Server'}
PROFILE_TITLE=${config.profileTitle || 'Best Growtopia Private Server ??'}
TAGLINE=${config.tagline || '?? Mulai Petualangan Baru Kamu di Magical GTPS! Nikmati Sensasi Main Growtopia Tanpa Batas, Fitur Role Keren, Komunitas Ramah & Admin Fast Response 24 Jam. Ayo Ajak Teman-Temanmu Dan Join Sekarang!'}
CATEGORIES=${config.categories || 'Growtopia • Magical Private Server • Community'}
COPYRIGHT_TEXT=${config.copyrightText || '© 2026 Copyright by Magical Private Server'}
GUIDE_TITLE=${config.guideTitle || 'Cara Bermain Magical PS'}

# URL Gambar & Musik Latar (Opsional)
BANNER_URL=${config.bannerUrl || '/banner.png'}
AVATAR_URL=${config.avatarUrl || '/logo.png'}
AUDIO_URL=${config.audioUrl || '/bgm.mp3'}
`;

  try {
    if (!GITHUB_TOKEN) {
      return res.status(200).json({
        success: true,
        message: 'Konfigurasi tersimpan lokal di browser (Set GITHUB_TOKEN di Vercel untuk auto-sync GitHub).'
      });
    }

    const headers = {
      'Authorization': `token ${GITHUB_TOKEN}`,
      'User-Agent': 'Vercel-Serverless-Function',
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    };

    let sha = null;
    try {
      const getRes = await fetch(`https://api.github.com/repos/${REPO}/contents/public/config.txt`, { headers });
      if (getRes.ok) {
        const data = await getRes.json();
        sha = data.sha;
      }
    } catch (_) {}

    const putBody = {
      message: `Update config.txt via Admin Dashboard (/admin) [${new Date().toISOString()}]`,
      content: Buffer.from(configTxtContent, 'utf-8').toString('base64'),
      ...(sha ? { sha } : {})
    };

    const putRes = await fetch(`https://api.github.com/repos/${REPO}/contents/public/config.txt`, {
      method: 'PUT',
      headers,
      body: JSON.stringify(putBody)
    });

    if (!putRes.ok) {
      const errData = await putRes.text();
      return res.status(500).json({ error: 'Gagal commit ke GitHub: ' + errData });
    }

    return res.status(200).json({
      success: true,
      message: 'Konfigurasi berhasil disimpan dan dipublish ke GitHub & Vercel!'
    });
  } catch (err) {
    return res.status(500).json({ error: err.message || 'Internal server error' });
  }
}
